### ISSUE TITLE
Add lilith to container registery

### ISSUE THREAD

**Issue by jimski427** [lilith-discord-bot/lilith#14]
**Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is.**
would like to have this added to a container registry for easy docker deployment

**Describe the solution you'd like A clear and concise description of what you want to happen.**
added to github container registry or docker hub.

**Comment by Mawco** [comment]
Hey! Sure, we could do that, i might start working on that later today, will close this issue once it's done.

**Comment by Mawco** [comment]
Waiting for review #24
