### ISSUE TITLE
Error when inputting command in Discord

### ISSUE THREAD

**Issue by AburaBoomer** [lilith-discord-bot/lilith#58]
**Describe the bug**
Whenever I'm trying to input a /command in Discord, the bot throws errors in the Lilith-Bot-1 container and Discord says that the application did not respond.

I followed your install steps from the NPM option.

Attached is the container log from the bot-1 container
[_lilith-bot-1_logs.txt](https://github.com/lilith-discord-bot/lilith/files/11867803/_lilith-bot-1_logs.txt)

Edit: .env
TOKEN=<redacted>

#Database
POSTGRES_HOST=d4 # Doesn't need to be set if running with Docker.
POSTGRES_USER=d4
POSTGRES_PASSWORD=d4
POSTGRES_DATABASE=d4
DATABASE_URL="postgresql://d4:d4@172.21.0.2:5432/d4"

#Cache
REDIS_HOST=redis_host # Doesn't need to be set if running with Docker.
REDIS_PORT=0000 # Doesn't need to be set if running with Docker.
REDIS_PASSWORD=d4

**Comment by FraWolf** [comment]
This error appears because the database's tables and stuff are not initialized, you should use `npx prisma migrate dev --name init_migration` and then starts your bot

**Comment by AburaBoomer** [comment]
Cheers for the reaction. That command did indeed fix the problem.
