### ISSUE TITLE
Feature Request - Notifications - Hell Tide and Legion Invasion - Specify region

### ISSUE THREAD

**Issue by WinterThaiger** [lilith-discord-bot/lilith#91]
**Is your feature request related to a problem? Please describe.**
I'm currently farming the region Scosglen for the mount barding specifically and would like to see an additional feature when selecting to get notified for either Hell Tide or Legion invasion instead of having to get alerted for all regions.

**Describe the solution you'd like**
When selecting the event option - Hell Tide or Legion Invasion, add an additional field - [Region] to be answered either by Fractured Peaks, Scosglen, Dry Steppes, Kehjistan, Hawezar, or All. This is for specific persons who is farming that specific region for any regional drops such as the mount barding.

**Comment by glazk0** [comment]
Hello, I think it's a niche feature to be honest, for now there is no real reason for us to add this kind of thing cause there is no really specific spot to farm theses.

**Comment by glazk0** [comment]
I keep the idea in mind (will add it to Trello) but I don't promise anything yet.
